#!/usr/bin/env python3
"""
Generate synthetic NetCDF test data for TIDE end-to-end integration tests.

Creates:
  1. synthetic_forcing.nc — A CF-compliant NetCDF-4 file with:
       - 2 time steps (0.0 and 3600.0 seconds since epoch)
       - 4×4 lat-lon grid (lats: -60, -20, 20, 60; lons: 0, 90, 180, 270)
       - 4 vertical levels (100000, 85000, 50000, 20000 Pa)
       - A "temperature" variable following an analytical function

  2. reference_output.nc — Precomputed reference for e2e comparison:
       - The analytically correct result at t=1800s (temporal midpoint)
       - Same grid as synthetic_forcing.nc (no regridding in simplest test)

The data follows a linear function in all dimensions:
    T(t, lat, lon, lev) = 250.0 + 0.1*lat + 0.01*lon + 0.001*lev + 10.0*(t/3600.0)

This makes temporal interpolation analytically verifiable:
    At t=1800 (midpoint), the exact result is:
    T(1800, lat, lon, lev) = 250.0 + 0.1*lat + 0.01*lon + 0.001*lev + 5.0

Usage:
    python3 generate_test_data.py [output_dir]

    output_dir defaults to the directory containing this script.

Requirements:
    netCDF4 (pip install netCDF4)
    numpy
"""

import os
import sys
import numpy as np

try:
    from netCDF4 import Dataset
except ImportError:
    print("ERROR: netCDF4 Python package is required.")
    print("Install with: pip install netCDF4")
    sys.exit(1)


def analytical_temperature(time_s, lat, lon, lev):
    """
    Compute the analytical temperature field.

    T(t, lat, lon, lev) = 250.0 + 0.1*lat + 0.01*lon + 0.001*lev + 10.0*(t/3600.0)

    Parameters
    ----------
    time_s : float
        Time in seconds since epoch.
    lat : array-like
        Latitude values in degrees.
    lon : array-like
        Longitude values in degrees.
    lev : array-like
        Vertical level values in Pa.

    Returns
    -------
    numpy.ndarray
        4D array with shape (1, nlev, nlat, nlon).
    """
    # Create mesh grids for broadcasting: (lev, lat, lon)
    lev_3d, lat_3d, lon_3d = np.meshgrid(lev, lat, lon, indexing="ij")
    field = (
        250.0 + 0.1 * lat_3d + 0.01 * lon_3d + 0.001 * lev_3d + 10.0 * (time_s / 3600.0)
    )
    return field


def create_synthetic_forcing(filepath, times, lats, lons, levels):
    """
    Create the synthetic forcing NetCDF file with CF-compliant metadata.
    """
    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("time", None)  # unlimited
    ds.createDimension("level", len(levels))
    ds.createDimension("lat", len(lats))
    ds.createDimension("lon", len(lons))

    # Coordinate variables
    time_var = ds.createVariable("time", "f8", ("time",))
    time_var.units = "seconds since 1970-01-01 00:00:00"
    time_var.calendar = "standard"
    time_var.long_name = "time"
    time_var.axis = "T"
    time_var[:] = times

    lat_var = ds.createVariable("lat", "f8", ("lat",))
    lat_var.units = "degrees_north"
    lat_var.long_name = "latitude"
    lat_var.axis = "Y"
    lat_var.standard_name = "latitude"
    lat_var[:] = lats

    lon_var = ds.createVariable("lon", "f8", ("lon",))
    lon_var.units = "degrees_east"
    lon_var.long_name = "longitude"
    lon_var.axis = "X"
    lon_var.standard_name = "longitude"
    lon_var[:] = lons

    lev_var = ds.createVariable("level", "f8", ("level",))
    lev_var.units = "Pa"
    lev_var.long_name = "pressure level"
    lev_var.axis = "Z"
    lev_var.positive = "down"
    lev_var.standard_name = "air_pressure"
    lev_var[:] = levels

    # Data variable
    temp_var = ds.createVariable(
        "temperature",
        "f8",
        ("time", "level", "lat", "lon"),
        fill_value=9.969209968386869e36,
    )
    temp_var.units = "K"
    temp_var.long_name = "air temperature"
    temp_var.standard_name = "air_temperature"
    temp_var.coordinates = "time level lat lon"

    # Fill data using analytical function
    for ti, t in enumerate(times):
        temp_var[ti, :, :, :] = analytical_temperature(t, lats, lons, levels)

    # Global attributes (CF conventions)
    ds.Conventions = "CF-1.8"
    ds.title = "TIDE synthetic test forcing data"
    ds.source = "Analytically generated for integration testing"
    ds.history = "Generated by generate_test_data.py"

    ds.close()
    print(f"  Created: {filepath}")


def create_reference_output(filepath, target_time, lats, lons, levels):
    """
    Create the reference output NetCDF file.

    This represents the expected pipeline output after temporal interpolation
    at t=target_time on the same grid (identity regridding).
    """
    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("level", len(levels))
    ds.createDimension("lat", len(lats))
    ds.createDimension("lon", len(lons))

    # Coordinate variables
    lat_var = ds.createVariable("lat", "f8", ("lat",))
    lat_var.units = "degrees_north"
    lat_var.long_name = "latitude"
    lat_var[:] = lats

    lon_var = ds.createVariable("lon", "f8", ("lon",))
    lon_var.units = "degrees_east"
    lon_var.long_name = "longitude"
    lon_var[:] = lons

    lev_var = ds.createVariable("level", "f8", ("level",))
    lev_var.units = "Pa"
    lev_var.long_name = "pressure level"
    lev_var[:] = levels

    # Reference temperature field at target_time
    temp_var = ds.createVariable("temperature", "f8", ("level", "lat", "lon"))
    temp_var.units = "K"
    temp_var.long_name = "reference air temperature at t=1800s"
    temp_var.description = (
        "Analytically computed temperature at t=1800s using "
        "T = 250.0 + 0.1*lat + 0.01*lon + 0.001*lev + 10.0*(t/3600.0)"
    )

    temp_var[:, :, :] = analytical_temperature(target_time, lats, lons, levels)

    # Global attributes
    ds.Conventions = "CF-1.8"
    ds.title = "TIDE reference output for e2e test validation"
    ds.source = "Analytically computed at t=1800s"
    ds.target_time_seconds = target_time
    ds.tolerance = 1.0e-10
    ds.history = "Generated by generate_test_data.py"

    ds.close()
    print(f"  Created: {filepath}")


def create_scrip_weight_file(filepath, n_src, n_dst, remap_method="Conservative"):
    """
    Create a synthetic SCRIP weight file for testing.

    Creates a simple identity-like mapping where each destination cell
    maps to a single source cell (one-to-one for min(n_src, n_dst) cells).
    For a more realistic test, also includes some cells with multiple sources.

    Format: standard SCRIP with n_s, n_a, n_b dimensions and
    src_address, dst_address, remap_matrix variables.
    """
    # Build a sparse weight matrix:
    # - First n_dst cells each get weight 1.0 from the corresponding source
    # - Plus some extra entries for cells that blend two sources
    src_addresses = []
    dst_addresses = []
    weights = []

    # Identity mapping for first min(n_src, n_dst) cells
    n_identity = min(n_src, n_dst)
    for i in range(n_identity):
        src_addresses.append(i + 1)  # 1-based
        dst_addresses.append(i + 1)  # 1-based
        weights.append(1.0)

    # Add a few blended entries: dst cell n_identity-1 also gets 0.3 from cell 0
    # and 0.7 from cell 1 (overwrite the identity for that cell to test blending)
    if n_identity >= 3:
        # Replace the last identity entry with a blend
        src_addresses[-1] = 1  # source cell 1 (1-based)
        weights[-1] = 0.6
        # Add second source for same destination
        src_addresses.append(2)  # source cell 2 (1-based)
        dst_addresses.append(n_identity)  # same dest (1-based)
        weights.append(0.4)

    n_s = len(src_addresses)

    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("n_s", n_s)
    ds.createDimension("n_a", n_src)
    ds.createDimension("n_b", n_dst)

    # Variables (1-based Fortran addresses)
    src_var = ds.createVariable("src_address", "i4", ("n_s",))
    src_var[:] = np.array(src_addresses, dtype=np.int32)

    dst_var = ds.createVariable("dst_address", "i4", ("n_s",))
    dst_var[:] = np.array(dst_addresses, dtype=np.int32)

    wgt_var = ds.createVariable("remap_matrix", "f8", ("n_s",))
    wgt_var[:] = np.array(weights, dtype=np.float64)

    # Global attributes
    ds.title = "TIDE synthetic SCRIP weight file"
    ds.map_method = remap_method
    ds.conventions = "SCRIP"

    ds.close()
    print(f"  Created: {filepath} (n_s={n_s}, n_a={n_src}, n_b={n_dst})")


def create_scrip_weight_file_2d(filepath, n_src, n_dst):
    """
    Create a SCRIP weight file with 2D remap_matrix(n_s, num_wts).
    Tests the 2D weight array reading path.
    """
    # Simple identity mapping
    n_s = min(n_src, n_dst)
    num_wts = 3  # Higher-order weights (only first column used)

    src_addresses = np.arange(1, n_s + 1, dtype=np.int32)
    dst_addresses = np.arange(1, n_s + 1, dtype=np.int32)
    # First column is the actual weight, others are higher-order (ignored)
    remap_matrix = np.zeros((n_s, num_wts), dtype=np.float64)
    remap_matrix[:, 0] = 1.0  # Identity weights in first column
    remap_matrix[:, 1] = 0.0  # Higher-order: zero
    remap_matrix[:, 2] = 0.0  # Higher-order: zero

    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    ds.createDimension("n_s", n_s)
    ds.createDimension("num_wts", num_wts)
    ds.createDimension("n_a", n_src)
    ds.createDimension("n_b", n_dst)

    src_var = ds.createVariable("src_address", "i4", ("n_s",))
    src_var[:] = src_addresses

    dst_var = ds.createVariable("dst_address", "i4", ("n_s",))
    dst_var[:] = dst_addresses

    wgt_var = ds.createVariable("remap_matrix", "f8", ("n_s", "num_wts"))
    wgt_var[:, :] = remap_matrix

    ds.title = "TIDE synthetic SCRIP weight file (2D remap_matrix)"
    ds.map_method = "Bilinear"
    ds.conventions = "SCRIP"

    ds.close()
    print(f"  Created: {filepath} (n_s={n_s}, num_wts={num_wts})")


def create_esmf_mesh_file(filepath, n_elements=100):
    """
    Create a synthetic ESMF mesh file for testing.

    Creates an unstructured mesh consisting of quadrilateral elements
    arranged in a regular grid pattern (for simplicity), with:
    - nodeCoords(nodeCount, coordDim) — node [lon, lat] pairs
    - elementConn(elementCount, maxNodePElement) — 1-based connectivity
    - numElementConn(elementCount) — nodes per element (all 4 for quads)

    The mesh covers a 10x10 grid of quadrilateral cells spanning
    lon=[0, 360] and lat=[-90, 90].
    """
    # Create a grid of nodes: (nx+1) x (ny+1) nodes for nx*ny quads
    nx = int(np.sqrt(n_elements))
    ny = n_elements // nx
    n_elements_actual = nx * ny
    n_nodes = (nx + 1) * (ny + 1)

    # Generate node coordinates
    lons = np.linspace(0.0, 360.0, nx + 1)
    lats = np.linspace(-90.0, 90.0, ny + 1)
    lon_grid, lat_grid = np.meshgrid(lons, lats)

    # Flatten to (nodeCount, 2) with [lon, lat] ordering (ESMF convention)
    node_coords = np.zeros((n_nodes, 2), dtype=np.float64)
    node_coords[:, 0] = lon_grid.flatten()  # longitude
    node_coords[:, 1] = lat_grid.flatten()  # latitude

    # Build element connectivity (1-based, 4 nodes per quad element)
    max_node_p_element = 4
    element_conn = np.zeros((n_elements_actual, max_node_p_element), dtype=np.int32)
    num_element_conn = np.full(n_elements_actual, 4, dtype=np.int32)

    for j in range(ny):
        for i in range(nx):
            elem_idx = j * nx + i
            # Node indices (0-based in the grid, converted to 1-based for ESMF)
            n0 = j * (nx + 1) + i  # bottom-left
            n1 = j * (nx + 1) + (i + 1)  # bottom-right
            n2 = (j + 1) * (nx + 1) + (i + 1)  # top-right
            n3 = (j + 1) * (nx + 1) + i  # top-left
            element_conn[elem_idx, :] = [n0 + 1, n1 + 1, n2 + 1, n3 + 1]

    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("nodeCount", n_nodes)
    ds.createDimension("elementCount", n_elements_actual)
    ds.createDimension("coordDim", 2)
    ds.createDimension("maxNodePElement", max_node_p_element)

    # Variables
    nc_var = ds.createVariable("nodeCoords", "f8", ("nodeCount", "coordDim"))
    nc_var[:, :] = node_coords

    ec_var = ds.createVariable("elementConn", "i4", ("elementCount", "maxNodePElement"))
    ec_var[:, :] = element_conn

    nec_var = ds.createVariable("numElementConn", "i4", ("elementCount",))
    nec_var[:] = num_element_conn

    # Global attributes
    ds.title = "TIDE synthetic ESMF mesh file"
    ds.meshName = "test_mesh"
    ds.conventions = "ESMF"

    ds.close()
    print(f"  Created: {filepath} (nodes={n_nodes}, elements={n_elements_actual})")


def create_esmf_grid_spec_file(filepath, nlat=18, nlon=36, with_corners=True):
    """
    Create a synthetic ESMF grid specification file for testing.

    Creates a regular lat-lon grid with:
    - grid_center_lat(grid_size) — cell center latitudes
    - grid_center_lon(grid_size) — cell center longitudes
    - grid_corner_lat(grid_size, grid_corners) — cell corner latitudes (optional)
    - grid_corner_lon(grid_size, grid_corners) — cell corner longitudes (optional)
    """
    grid_size = nlat * nlon

    # Cell centers
    dlat = 180.0 / nlat
    dlon = 360.0 / nlon
    center_lats_1d = np.linspace(-90.0 + dlat / 2.0, 90.0 - dlat / 2.0, nlat)
    center_lons_1d = np.linspace(dlon / 2.0, 360.0 - dlon / 2.0, nlon)

    lon_grid, lat_grid = np.meshgrid(center_lons_1d, center_lats_1d)
    center_lats = lat_grid.flatten()
    center_lons = lon_grid.flatten()

    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("grid_size", grid_size)

    # Center coordinate variables
    clat_var = ds.createVariable("grid_center_lat", "f8", ("grid_size",))
    clat_var.units = "degrees"
    clat_var[:] = center_lats

    clon_var = ds.createVariable("grid_center_lon", "f8", ("grid_size",))
    clon_var.units = "degrees"
    clon_var[:] = center_lons

    # Corner coordinates (4 corners per cell for a regular lat-lon grid)
    if with_corners:
        grid_corners = 4
        ds.createDimension("grid_corners", grid_corners)

        corner_lats = np.zeros((grid_size, grid_corners), dtype=np.float64)
        corner_lons = np.zeros((grid_size, grid_corners), dtype=np.float64)

        for j in range(nlat):
            for i in range(nlon):
                idx = j * nlon + i
                lat_c = center_lats_1d[j]
                lon_c = center_lons_1d[i]
                half_dlat = dlat / 2.0
                half_dlon = dlon / 2.0

                # Corners: SW, SE, NE, NW
                corner_lats[idx, 0] = lat_c - half_dlat
                corner_lats[idx, 1] = lat_c - half_dlat
                corner_lats[idx, 2] = lat_c + half_dlat
                corner_lats[idx, 3] = lat_c + half_dlat

                corner_lons[idx, 0] = lon_c - half_dlon
                corner_lons[idx, 1] = lon_c + half_dlon
                corner_lons[idx, 2] = lon_c + half_dlon
                corner_lons[idx, 3] = lon_c - half_dlon

        clat_corner_var = ds.createVariable(
            "grid_corner_lat", "f8", ("grid_size", "grid_corners")
        )
        clat_corner_var.units = "degrees"
        clat_corner_var[:, :] = corner_lats

        clon_corner_var = ds.createVariable(
            "grid_corner_lon", "f8", ("grid_size", "grid_corners")
        )
        clon_corner_var.units = "degrees"
        clon_corner_var[:, :] = corner_lons

    # Global attributes
    ds.title = "TIDE synthetic ESMF grid spec file"
    ds.conventions = "SCRIP"

    ds.close()
    corners_str = "with corners" if with_corners else "no corners"
    print(f"  Created: {filepath} ({nlat}x{nlon}, {corners_str})")


def create_scrip_bilinear_weight_file(filepath, n_src, n_dst):
    """
    Create a SCRIP weight file for bilinear remapping with 1D remap_matrix.

    For bilinear remapping, each destination cell typically maps to 4 source
    cells with weights that sum to 1.0. This generates a realistic pattern
    where destination cells use bilinear interpolation from a 2D source grid.
    """
    src_addresses = []
    dst_addresses = []
    weights = []

    # Create a pattern where each destination gets 4 source contributions
    # simulating bilinear interpolation from a regular grid
    n_src_side = int(np.sqrt(n_src))
    n_dst_side = int(np.sqrt(n_dst))

    for j in range(n_dst_side):
        for i in range(n_dst_side):
            dst_cell = j * n_dst_side + i + 1  # 1-based

            # Bilinear weights from 4 surrounding source cells
            # Map destination to fractional position in source grid
            src_j = min(j, n_src_side - 2)
            src_i = min(i, n_src_side - 2)

            # Fractional positions within the source cell
            frac_j = (j / max(n_dst_side - 1, 1)) * (n_src_side - 1) - src_j
            frac_i = (i / max(n_dst_side - 1, 1)) * (n_src_side - 1) - src_i
            frac_j = max(0.0, min(1.0, frac_j))
            frac_i = max(0.0, min(1.0, frac_i))

            # Four corner source cells (1-based)
            s00 = src_j * n_src_side + src_i + 1
            s01 = src_j * n_src_side + (src_i + 1) + 1
            s10 = (src_j + 1) * n_src_side + src_i + 1
            s11 = (src_j + 1) * n_src_side + (src_i + 1) + 1

            # Bilinear weights
            w00 = (1.0 - frac_j) * (1.0 - frac_i)
            w01 = (1.0 - frac_j) * frac_i
            w10 = frac_j * (1.0 - frac_i)
            w11 = frac_j * frac_i

            # Only add non-zero weights
            for src_cell, w in [(s00, w00), (s01, w01), (s10, w10), (s11, w11)]:
                if w > 1e-15 and src_cell <= n_src:
                    src_addresses.append(src_cell)
                    dst_addresses.append(dst_cell)
                    weights.append(w)

    n_s = len(src_addresses)

    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("n_s", n_s)
    ds.createDimension("n_a", n_src)
    ds.createDimension("n_b", n_dst)

    # Variables
    src_var = ds.createVariable("src_address", "i4", ("n_s",))
    src_var[:] = np.array(src_addresses, dtype=np.int32)

    dst_var = ds.createVariable("dst_address", "i4", ("n_s",))
    dst_var[:] = np.array(dst_addresses, dtype=np.int32)

    wgt_var = ds.createVariable("remap_matrix", "f8", ("n_s",))
    wgt_var[:] = np.array(weights, dtype=np.float64)

    # Global attributes
    ds.title = "TIDE synthetic SCRIP bilinear weight file"
    ds.map_method = "Bilinear"
    ds.conventions = "SCRIP"

    ds.close()
    print(f"  Created: {filepath} (n_s={n_s}, n_a={n_src}, n_b={n_dst})")


def create_second_forcing_file(filepath, times, lats, lons, levels):
    """
    Create a second synthetic forcing NetCDF file with a different field.

    Uses a different analytical function for the 'emissions' variable:
        E(t, lat, lon, lev) = 1.0e-6 * (1.0 + 0.01*lat + 0.005*lon + 5.0*(t/3600.0))

    This provides a distinct forcing stream for multi-stream testing.
    """
    ds = Dataset(filepath, "w", format="NETCDF4_CLASSIC")

    # Dimensions
    ds.createDimension("time", None)
    ds.createDimension("level", len(levels))
    ds.createDimension("lat", len(lats))
    ds.createDimension("lon", len(lons))

    # Coordinate variables
    time_var = ds.createVariable("time", "f8", ("time",))
    time_var.units = "seconds since 1970-01-01 00:00:00"
    time_var.calendar = "standard"
    time_var[:] = times

    lat_var = ds.createVariable("lat", "f8", ("lat",))
    lat_var.units = "degrees_north"
    lat_var.long_name = "latitude"
    lat_var[:] = lats

    lon_var = ds.createVariable("lon", "f8", ("lon",))
    lon_var.units = "degrees_east"
    lon_var.long_name = "longitude"
    lon_var[:] = lons

    lev_var = ds.createVariable("level", "f8", ("level",))
    lev_var.units = "Pa"
    lev_var.long_name = "pressure level"
    lev_var[:] = levels

    # Emissions data variable
    emis_var = ds.createVariable(
        "emissions",
        "f8",
        ("time", "level", "lat", "lon"),
        fill_value=9.969209968386869e36,
    )
    emis_var.units = "kg m-2 s-1"
    emis_var.long_name = "surface emissions flux"

    # Fill data: E(t, lat, lon, lev) = 1e-6 * (1 + 0.01*lat + 0.005*lon + 5*(t/3600))
    for ti, t in enumerate(times):
        lev_3d, lat_3d, lon_3d = np.meshgrid(levels, lats, lons, indexing="ij")
        field = 1.0e-6 * (1.0 + 0.01 * lat_3d + 0.005 * lon_3d + 5.0 * (t / 3600.0))
        emis_var[ti, :, :, :] = field

    # Global attributes
    ds.Conventions = "CF-1.8"
    ds.title = "TIDE synthetic emissions forcing data"
    ds.source = "Analytically generated for multi-stream testing"

    ds.close()
    print(f"  Created: {filepath}")


def main():
    # Determine output directory
    if len(sys.argv) > 1:
        output_dir = sys.argv[1]
    else:
        output_dir = os.path.dirname(os.path.abspath(__file__))

    os.makedirs(output_dir, exist_ok=True)

    # Grid parameters
    times = np.array([0.0, 3600.0])  # 2 timesteps (seconds)
    lats = np.array([-60.0, -20.0, 20.0, 60.0])  # 4 latitudes
    lons = np.array([0.0, 90.0, 180.0, 270.0])  # 4 longitudes
    levels = np.array([100000.0, 85000.0, 50000.0, 20000.0])  # 4 pressure levels (Pa)

    target_time = 1800.0  # Midpoint for temporal interpolation

    print("Generating TIDE synthetic test data...")
    print(f"  Output directory: {output_dir}")
    print(
        f"  Grid: {len(lats)}x{len(lons)} lat-lon, {len(levels)} levels, {len(times)} timesteps"
    )
    print(f"  Reference time: {target_time}s")
    print()

    # Create synthetic forcing file
    forcing_path = os.path.join(output_dir, "synthetic_forcing.nc")
    create_synthetic_forcing(forcing_path, times, lats, lons, levels)

    # Create reference output file
    reference_path = os.path.join(output_dir, "reference_output.nc")
    create_reference_output(reference_path, target_time, lats, lons, levels)

    # Create second forcing file for multi-stream testing
    emissions_path = os.path.join(output_dir, "synthetic_emissions.nc")
    create_second_forcing_file(emissions_path, times, lats, lons, levels)

    # Create SCRIP weight test files
    print()
    print("Generating SCRIP weight test files...")
    scrip_path = os.path.join(output_dir, "scrip_weights_conservative.nc")
    create_scrip_weight_file(
        scrip_path, n_src=16, n_dst=16, remap_method="Conservative"
    )

    scrip_2d_path = os.path.join(output_dir, "scrip_weights_bilinear_2d.nc")
    create_scrip_weight_file_2d(scrip_2d_path, n_src=16, n_dst=16)

    # Production-readiness test files (task 19.1)
    # SCRIP conservative weight file for integration tests
    scrip_conserve_path = os.path.join(output_dir, "scrip_conserve_weights.nc")
    create_scrip_weight_file(
        scrip_conserve_path, n_src=16, n_dst=16, remap_method="Conservative"
    )

    # SCRIP bilinear weight file for integration tests
    scrip_bilinear_path = os.path.join(output_dir, "scrip_bilinear_weights.nc")
    create_scrip_bilinear_weight_file(scrip_bilinear_path, n_src=16, n_dst=16)

    # Create ESMF test files
    print()
    print("Generating ESMF test files...")
    esmf_mesh_path = os.path.join(output_dir, "esmf_mesh_100cells.nc")
    create_esmf_mesh_file(esmf_mesh_path, n_elements=100)

    esmf_grid_spec_path = os.path.join(output_dir, "esmf_grid_spec.nc")
    create_esmf_grid_spec_file(esmf_grid_spec_path, nlat=18, nlon=36, with_corners=True)

    esmf_grid_spec_no_corners_path = os.path.join(
        output_dir, "esmf_grid_spec_no_corners.nc"
    )
    create_esmf_grid_spec_file(
        esmf_grid_spec_no_corners_path, nlat=4, nlon=8, with_corners=False
    )

    # Print summary for verification
    print()
    print("Verification of analytical function:")
    print(
        f"  T(0, -60, 0, 100000)    = {analytical_temperature(0, lats, lons, levels)[0, 0, 0]:.6f}"
    )
    print(
        f"  T(3600, 60, 270, 20000) = {analytical_temperature(3600, lats, lons, levels)[3, 3, 3]:.6f}"
    )
    print(
        f"  T(1800, 0, 0, 50000)    = {analytical_temperature(1800, lats, lons, levels)[2, 2, 0]:.6f}"
    )
    print()
    print("Done.")


if __name__ == "__main__":
    main()
